/* Load this script using conditional IE comments if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'phpbb\'">' + entity + '</span>' + html;
	}
	var icons = {
			'custom-none' : '&#xe000;',
			'custom-bootstrap' : '&#xe001;',
			'custom-less_c' : '&#xe002;',
			'custom-w3c' : '&#xe003;',
			'custom-pencil' : '&#xe004;',
			'custom-pencil-2' : '&#xe005;',
			'custom-image' : '&#xe006;',
			'custom-image-2' : '&#xe007;',
			'custom-images' : '&#xe008;',
			'custom-pacman' : '&#xe009;',
			'custom-diamonds' : '&#xe00a;',
			'custom-clubs' : '&#xe00b;',
			'custom-spades' : '&#xe00c;',
			'custom-tags' : '&#xe00d;',
			'custom-tag' : '&#xe00e;',
			'custom-folder-open' : '&#xe00f;',
			'custom-folder' : '&#xe010;',
			'custom-library' : '&#xe011;',
			'custom-feed' : '&#xe012;',
			'custom-podcast' : '&#xe013;',
			'custom-connection' : '&#xe014;',
			'custom-coin' : '&#xe015;',
			'custom-pushpin' : '&#xe016;',
			'custom-location' : '&#xe017;',
			'custom-location-2' : '&#xe018;',
			'custom-map' : '&#xe019;',
			'custom-map-2' : '&#xe01a;',
			'custom-history' : '&#xe01b;',
			'custom-clock' : '&#xe01c;',
			'custom-clock-2' : '&#xe01d;',
			'custom-alarm' : '&#xe01e;',
			'custom-alarm-2' : '&#xe01f;',
			'custom-stopwatch' : '&#xe020;',
			'custom-bell' : '&#xe021;',
			'custom-calendar' : '&#xe022;',
			'custom-calendar-2' : '&#xe023;',
			'custom-screen' : '&#xe024;',
			'custom-laptop' : '&#xe025;',
			'custom-mobile' : '&#xe026;',
			'custom-mobile-2' : '&#xe027;',
			'custom-tablet' : '&#xe028;',
			'custom-tv' : '&#xe029;',
			'custom-spinner' : '&#xe02a;',
			'custom-busy' : '&#xe02b;',
			'custom-spinner-2' : '&#xe02c;',
			'custom-spinner-3' : '&#xe02d;',
			'custom-spinner-4' : '&#xe02e;',
			'custom-spinner-5' : '&#xe02f;',
			'custom-spinner-6' : '&#xe030;',
			'custom-redo' : '&#xe031;',
			'custom-undo' : '&#xe032;',
			'custom-zoom-out' : '&#xe033;',
			'custom-zoom-in' : '&#xe034;',
			'custom-search' : '&#xe035;',
			'custom-quotes-left' : '&#xe036;',
			'custom-users' : '&#xe037;',
			'custom-user' : '&#xe038;',
			'custom-users-2' : '&#xe039;',
			'custom-user-2' : '&#xe03a;',
			'custom-bubbles' : '&#xe03b;',
			'custom-bubbles-2' : '&#xe03c;',
			'custom-bubble' : '&#xe03d;',
			'custom-bubbles-3' : '&#xe03e;',
			'custom-bubble-2' : '&#xe03f;',
			'custom-bubbles-4' : '&#xe040;',
			'custom-wand' : '&#xe041;',
			'custom-stats' : '&#xe042;',
			'custom-bars' : '&#xe043;',
			'custom-bars-2' : '&#xe044;',
			'custom-list' : '&#xe045;',
			'custom-list-2' : '&#xe046;',
			'custom-numbered-list' : '&#xe047;',
			'custom-menu' : '&#xe048;',
			'custom-menu-2' : '&#xe049;',
			'custom-link' : '&#xe04a;',
			'custom-earth' : '&#xe04b;',
			'custom-happy' : '&#xe04c;',
			'custom-happy-2' : '&#xe04d;',
			'custom-smiley' : '&#xe04e;',
			'custom-smiley-2' : '&#xe04f;',
			'custom-tongue' : '&#xe050;',
			'custom-tongue-2' : '&#xe051;',
			'custom-sad' : '&#xe052;',
			'custom-sad-2' : '&#xe053;',
			'custom-wink' : '&#xe054;',
			'custom-wink-2' : '&#xe055;',
			'custom-grin' : '&#xe056;',
			'custom-grin-2' : '&#xe057;',
			'custom-cool' : '&#xe058;',
			'custom-eye' : '&#xe059;',
			'custom-eye-blocked' : '&#xe05a;',
			'custom-eye-2' : '&#xe05b;',
			'custom-switch' : '&#xe05c;',
			'custom-angry' : '&#xe05d;',
			'custom-angry-2' : '&#xe05e;',
			'custom-cool-2' : '&#xe05f;',
			'custom-evil' : '&#xe060;',
			'custom-evil-2' : '&#xe061;',
			'custom-shocked' : '&#xe062;',
			'custom-shocked-2' : '&#xe063;',
			'custom-confused' : '&#xe064;',
			'custom-confused-2' : '&#xe065;',
			'custom-neutral' : '&#xe066;',
			'custom-neutral-2' : '&#xe067;',
			'custom-wondering' : '&#xe068;',
			'custom-wondering-2' : '&#xe069;',
			'custom-spell-check' : '&#xe06a;',
			'custom-checkmark' : '&#xe06b;',
			'custom-checkmark-2' : '&#xe06c;',
			'custom-checkbox-checked' : '&#xe06d;',
			'custom-checkbox-unchecked' : '&#xe06e;',
			'custom-checkbox-partial' : '&#xe06f;',
			'custom-radio-checked' : '&#xe070;',
			'custom-radio-unchecked' : '&#xe071;',
			'custom-crop' : '&#xe072;',
			'custom-scissors' : '&#xe073;',
			'custom-font' : '&#xe074;',
			'custom-text-height' : '&#xe075;',
			'custom-text-width' : '&#xe076;',
			'custom-bold' : '&#xe077;',
			'custom-underline' : '&#xe078;',
			'custom-italic' : '&#xe079;',
			'custom-strikethrough' : '&#xe07a;',
			'custom-right-to-left' : '&#xe07b;',
			'custom-left-to-right' : '&#xe07c;',
			'custom-code' : '&#xe07d;',
			'custom-embed' : '&#xe07e;',
			'custom-console' : '&#xe07f;',
			'custom-new-tab' : '&#xe080;',
			'custom-html5' : '&#xe081;',
			'custom-html5-2' : '&#xe082;',
			'custom-css3' : '&#xe083;',
			'custom-chrome' : '&#xe084;',
			'custom-firefox' : '&#xe085;',
			'custom-IE' : '&#xe086;',
			'custom-opera' : '&#xe087;',
			'custom-safari' : '&#xe088;',
			'custom-IcoMoon' : '&#xe089;',
			'custom-earth-2' : '&#xe08a;',
			'custom-target' : '&#xe08b;',
			'custom-list-3' : '&#xe08c;',
			'custom-smiley-3' : '&#xe08d;',
			'custom-image-3' : '&#xe08e;',
			'custom-equalizer' : '&#xe08f;',
			'custom-link-2' : '&#xe090;',
			'custom-at' : '&#xe091;',
			'custom-switch-2' : '&#xe092;',
			'custom-apple' : '&#xe093;',
			'custom-paperclip' : '&#xe094;',
			'custom-code-2' : '&#xe095;',
			'custom-dashboard' : '&#xe096;',
			'custom-meter2' : '&#xe097;',
			'custom-meter' : '&#xe098;',
			'custom-rocket' : '&#xe099;',
			'custom-settings' : '&#xe09a;',
			'custom-equalizer-2' : '&#xe09b;',
			'custom-warning' : '&#xe09c;',
			'custom-notification' : '&#xe09d;',
			'custom-question' : '&#xe09e;',
			'custom-info' : '&#xe09f;',
			'custom-info-2' : '&#xe0a0;',
			'custom-blocked' : '&#xe0a1;',
			'custom-cancel-circle' : '&#xe0a2;',
			'custom-checkmark-circle' : '&#xe0a3;',
			'custom-spam' : '&#xe0a4;',
			'custom-enter' : '&#xe0a5;',
			'custom-exit' : '&#xe0a6;',
			'custom-shuffle' : '&#xe0a7;',
			'custom-tab' : '&#xe0a8;',
			'custom-quill' : '&#xe0a9;',
			'custom-forjq' : '&#xe0aa;',
			'custom-forphp' : '&#xe0ab;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/custom-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};